Lesson 3. Task 18-20.
AnastasiyaIlkevich/learning_java pull request #3
Opened 2021-03-09 17:29 UTC by AnastasiyaIlkevich

check please)

2021-03-18 18:36 UTC, JuliaOnix commented on Lesson3/src/nastya/lesson3/homework/Task21StringBuilder.java
> +        long start = System.nanoTime();
**Where are the cycles?)**

2021-03-18 18:49 UTC, JuliaOnix commented on Lesson3/src/nastya/lesson3/homework/Task21StringBuilder.java
> +    private static String cycleString(String str1, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10) {
Where are the cycles?

2021-04-10 16:04 UTC, RomanKashenok requested changes

2021-04-10 16:04 UTC, RomanKashenok commented on Lesson3/src/nastya/lesson3/homework/Task21StringBuilder.java
> +        System.out.println(cycleString(str1, str2, str3, str4, str5, str6, str7, str8, str9, str10));
под "многократное сложение" имеется в виду примерно 10_000 и больше конкатенаций. Убери все эти сложения "руками" и сделай все конкатенации в цикле

2021-04-10 16:04 UTC, RomanKashenok commented on Lesson3/src/nastya/lesson3/homework/Task23TagsAndParagraph.java
> +        System.out.println(str.replaceAll("</?p( id=”p[1-9]+”)?>|</?div>|</?p( id=”[a-z]+”)?>", "<p>"));
слишком сложное и не универсальное регулярное выражение. 
код может выглядеть и так: 
"<p id='qwe' class='test_class example" style="color:red, border: 1px solid"> слово </p>

2021-04-11 16:35 UTC, AnastasiyaIlkevich commented on Lesson3/src/nastya/lesson3/homework/Task18PunctuationMarks.java
> +            for (char value : symbol) {
Исправила

2021-04-11 16:36 UTC, AnastasiyaIlkevich commented on Lesson3/src/nastya/lesson3/homework/Task19WordCounter.java
> +            if (str.charAt(i) == ' ' && str.charAt(i + 1) != ' ') {
Исправила

2021-04-11 16:36 UTC, AnastasiyaIlkevich commented on Lesson3/src/nastya/lesson3/homework/Task21StringBuilder.java
> +        System.out.println(cycleString(str1, str2, str3, str4, str5, str6, str7, str8, str9, str10));
Исправила

2021-04-11 16:36 UTC, AnastasiyaIlkevich commented on Lesson3/src/nastya/lesson3/homework/Task21StringBuilder.java
> +    private static String cycleString(String str1, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10) {
Исправила

2021-04-11 16:36 UTC, AnastasiyaIlkevich commented on Lesson3/src/nastya/lesson3/homework/Task23TagsAndParagraph.java
> +        System.out.println(str.replaceAll("</?p( id=”p[1-9]+”)?>|</?div>|</?p( id=”[a-z]+”)?>", "<p>"));
Исправила

2022-07-26 09:30 UTC, merged